### ISSUE TITLE
device-drama does not work with Elvish shell

### ISSUE THREAD

**Issue by I-use-Arch-btw-00111** [8tm/device-drama#8]
I got an error while trying to run device-drama on my Elvish 0.17.0 environment. Here is the output I got:

**~> device-drama
Traceback (most recent call last):
  File "/home/main/.local/bin/device-drama", line 8, in <module>
    sys.exit(main())
  File "/home/main/.local/pipx/venvs/device-drama/lib/python3.10/site-packages/device_drama/main.py", line 249, in main
    screen = '\n'.join(generate_screen(plugin_modules))
  File "/home/main/.local/pipx/venvs/device-drama/lib/python3.10/site-packages/device_drama/main.py", line 154, in generate_screen
    output: List[Dict[str, str]] = dd_plugin.run()
  File "/home/main/.local/pipx/venvs/device-drama/lib/python3.10/site-packages/device_drama/plugins/05_Applications/01_shell_info.py", line 33, in run
    'text': self.get_shell_info(),
  File "/home/main/.local/pipx/venvs/device-drama/lib/python3.10/site-packages/device_drama/plugins/05_Applications/01_shell_info.py", line 25, in get_shell_info
    shell_version = shell_version_output.split()[3].split('(')[0]
IndexError: list index out of range
Exception: device-drama exited with 1
[tty 1], line 1: device-drama**

In bash, device-drama works without any errors.

**Comment by 8tm** [comment]
Hi,

fixed in version device-drama==24.5.13

Please let me know if you will find any other issues :)

If it's fine - please close this issue.

**Comment by I-use-Arch-btw-00111** [comment]
Indeed, it works now.
Thank you for fixing this issue :)

**~> device-drama
 Device-Drama v24.5.13        (http://github.com/8tm/device-drama)                                                                                                                                                                           
                                                                                                                                                                                                                                             
         Main Hardware                                                                                                                                                                                                                       
  MoBo: To Be Filled By O.E.M. B150 Gaming K4/Hyper                                                                                                                                                                                          
   CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz                                                                                                                                                                                              
   GPU: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (Used 0 GB of 6 GB)                                                                                                                                                                            
   RAM: Used 4.73 GB of 15.56 GB (30.38 %)                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
         Disks                                                                                                                                                                                                                               
  ID Model                      Size Tran  RPM   Real Size  Real Used  Real Free Used% Free% Mount Mount path                                                                                                                                
   1 TS240GSSD220S            ------ SATA  ----  223.57 GB  223.57 GB        0 B  100%    0%    NO                                                                                                                                           
   2 TOSHIBA DT01ACA100       ------ SATA  ----  931.51 GB  901.91 GB   29.60 GB   97%    3%   YES /                                                                                                                                         
   3 ST1000DM003-1CH162       ------ SATA  ----  931.51 GB  931.44 GB   72.58 MB  100%    0%   YES /boot/efi                                                                                                                                 
                                                                                                                                                                                                                                             
         Monitors                                                                                                                                                                                                                            
   Orientation:  ⯳                                                                                                                                                                                                                           
    Resolution: 1920x1080 (1920x1080)                                                                                                                                                                                                        
    Monitor  1: G27FC A              [ HDMI-0 ] [1920x1080] [Constructed: 2023-01]                                                                                                                                                           
                                                                                                                                                                                                                                             
         Operating System                                                                                                                                                                                                                    
  Distribution: Linux Mint                                                                                                                                                                                                                   
  Architecture: x86_64                                                                                                                                                                                                                       
     Code Name: Virginia                                                                                                                                                                                                                     
        Kernel: 6.5.0-1020-oem                                                                                                                                                                                                               
        Uptime: 0 days, 04:13:30                                                                                                                                                                                                             
      Packages: 2447 (dpkg), 1 (flatpak)                                                                                                                                                                                                     
         Theme: Mint-Y-Aqua                                                                                                                                                                                                                  
         Icons: Mint-Y-Sand                                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
         Applications                                                                                                                                                                                                                        
         Shell: Elvish 0.17.0+Ubuntu-1                                                                                                                                                                                                       
            WM: i3                                                                                                                                                                                                                           
      Terminal: xfce4-terminal

~>**
